# Generated by Django 3.1.2 on 2020-11-11 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('status', models.BooleanField(db_index=True, default=True, help_text='状态', verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='用户唯一标识', primary_key=True, serialize=False, unique=True, verbose_name='用户标识')),
                ('account', models.CharField(db_index=True, help_text='用户名', max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='登录密码', max_length=32, verbose_name='登录密码')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (0, '管理员')], db_index=True, default=1, help_text='用户类型', verbose_name='用户类型')),
                ('name', models.CharField(blank=True, db_index=True, help_text='用户姓名', max_length=32, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, db_index=True, help_text='用户电话', max_length=11, null=True, verbose_name='联系电话')),
                ('user_level', models.IntegerField(choices=[(0, '钻石用户'), (1, '重要用户'), (2, '一般用户')], db_index=True, default=2, help_text='用户级别', verbose_name='用户级别')),
                ('user_status', models.IntegerField(choices=[(0, '未验证'), (1, '已激活'), (2, '已禁用'), (3, '已删除'), (4, '已分配')], default=1, verbose_name='用户状态')),
                ('introduction', models.TextField(blank=True, help_text='用户简介', max_length=200, null=True, verbose_name='用户简介')),
                ('city', models.CharField(blank=True, help_text='用户城市', max_length=32, null=True, verbose_name='注册城市')),
                ('cert_type', models.IntegerField(blank=True, choices=[(0, '居民身份证'), (1, '护照')], default=0, help_text='证件类型', verbose_name='证件类型')),
                ('cert_number', models.CharField(blank=True, help_text='证件号码', max_length=32, null=True, verbose_name='证件号码')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
