# Generated by Django 3.1.3 on 2020-12-06 14:39

from django.db import migrations, models
import django.db.models.deletion
import server.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='收入明细标识', primary_key=True, serialize=False, unique=True, verbose_name='收入明细标识')),
                ('date', models.DateField(db_index=True, help_text='日期', unique=True, verbose_name='日期')),
                ('city', models.CharField(help_text='地域', max_length=32, null=True, verbose_name='地域')),
                ('task_type', models.IntegerField(choices=[(0, '技术交流'), (1, '学术探讨'), (2, '社会实践'), (3, '公益志愿者'), (4, '游玩')], db_index=True, default=0, help_text='召集令类型', verbose_name='召集令类型')),
                ('task_number', models.IntegerField(help_text='达成次数', verbose_name='达成次数')),
                ('cost', models.IntegerField(help_text='收入', verbose_name='收入')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='用户唯一标识', primary_key=True, serialize=False, unique=True, verbose_name='用户标识')),
                ('account', models.CharField(db_index=True, help_text='用户名', max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(help_text='登录密码', max_length=32, verbose_name='登录密码')),
                ('user_type', models.IntegerField(choices=[(1, '普通用户'), (0, '管理员')], default=1, help_text='用户类型', verbose_name='用户类型')),
                ('user_name', models.CharField(blank=True, help_text='用户姓名', max_length=32, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, help_text='用户电话', max_length=11, null=True, verbose_name='联系电话')),
                ('user_level', models.IntegerField(choices=[(0, '钻石用户'), (1, '重要用户'), (2, '一般用户')], db_index=True, default=2, help_text='用户级别', verbose_name='用户级别')),
                ('introduction', models.TextField(blank=True, help_text='用户简介', max_length=200, null=True, verbose_name='用户简介')),
                ('city', models.CharField(blank=True, help_text='用户城市', max_length=32, null=True, verbose_name='注册城市')),
                ('cert_type', models.IntegerField(blank=True, choices=[(0, '居民身份证'), (1, '护照')], default=0, help_text='证件类型', verbose_name='证件类型')),
                ('cert_number', models.CharField(blank=True, help_text='证件号码', max_length=32, null=True, verbose_name='证件号码')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='请求标识', primary_key=True, serialize=False, unique=True, verbose_name='请求标识')),
                ('description', models.TextField(blank=True, help_text='请求描述', max_length=200, null=True, verbose_name='请求描述')),
                ('request_status', models.IntegerField(choices=[(0, '待处理'), (1, '同意'), (2, '拒绝'), (3, '取消')], default=0, help_text='请求状态', verbose_name='请求状态')),
                ('requester_name', models.CharField(blank=True, help_text='接令人姓名', max_length=32, null=True, verbose_name='接令人姓名')),
                ('requester', models.ForeignKey(help_text='请求者', on_delete=django.db.models.deletion.CASCADE, to='server.profile', verbose_name='请求者')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='召集令唯一标识', primary_key=True, serialize=False, unique=True, verbose_name='召集令标识')),
                ('task_type', models.IntegerField(choices=[(0, '技术交流'), (1, '学术探讨'), (2, '社会实践'), (3, '公益志愿者'), (4, '游玩')], default=0, help_text='召集令类型', verbose_name='召集令类型')),
                ('task_name', models.CharField(blank=True, help_text='召集令名称', max_length=32, null=True, verbose_name='召集令名称')),
                ('description', models.TextField(blank=True, help_text='召集令描述', max_length=200, null=True, verbose_name='召集令描述')),
                ('cur_people', models.IntegerField(help_text='当前召集人数', verbose_name='当前召集人数')),
                ('max_people', models.IntegerField(help_text='最大召集人数', verbose_name='最大召集人数')),
                ('start_time', models.DateField(blank=True, help_text='开始日期', null=True, verbose_name='开始日期')),
                ('end_time', models.DateField(blank=True, help_text='结束日期', null=True, verbose_name='结束日期')),
                ('task_status', models.IntegerField(choices=[(1, '已完成'), (0, '待响应'), (2, '已取消'), (3, '已逾期')], default=0, help_text='召集令状态', verbose_name='召集令状态')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=server.models.user_directory_path, verbose_name='介绍图片')),
                ('master', models.ForeignKey(help_text='令主', on_delete=django.db.models.deletion.CASCADE, to='server.profile', verbose_name='令主')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='召集成功标识', primary_key=True, serialize=False, unique=True, verbose_name='召集成功标识')),
                ('master', models.CharField(help_text='令主标识', max_length=32, verbose_name='令主标识')),
                ('slave', models.CharField(help_text='接令用户标识', max_length=32, verbose_name='接令用户标识')),
                ('master_cost', models.IntegerField(help_text='令主支付费用', verbose_name='令主支付费用')),
                ('slave_cost', models.IntegerField(help_text='接令用户支付费用', verbose_name='接令用户支付费用')),
                ('complete_date', models.DateField(help_text='达成日期', verbose_name='达成日期')),
                ('request', models.OneToOneField(help_text='请求标识', on_delete=django.db.models.deletion.CASCADE, to='server.request', verbose_name='请求标识')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='request',
            name='task',
            field=models.ForeignKey(help_text='召集令', on_delete=django.db.models.deletion.CASCADE, to='server.task', verbose_name='召集令'),
        ),
    ]
