# Generated by Django 3.1.3 on 2020-12-07 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20201206_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success',
            name='request',
            field=models.ForeignKey(help_text='请求标识', on_delete=django.db.models.deletion.CASCADE, to='server.request', verbose_name='请求标识'),
        ),
    ]
