# Generated by Django 3.1.3 on 2020-12-07 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_auto_20201207_1321'),
    ]

    operations = [
    ]
