# Generated by Django 3.1.3 on 2020-12-14 14:02

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_auto_20201214_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='photo',
            field=models.CharField(blank=True, default='', max_length=163840, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
